global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    infra: devops

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'client.ru'
    static_configs:
      - targets: ['client.ru:443']
    scheme: https
    metrics_path: /metrics
    basic_auth:
      username: 'user' #указать пользователя
      password: 'password' #указать пароль

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://client.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [instance]
        target_label: resource_url
      - regex: ^http://(.+)$
        replacement: $1
        target_label: resource_url

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

remote_write:
  - url: "http://victoria_metrics:8428/api/v1/write"