version: "3"

networks:
  loki:

volumes:
  grafana:
  provisioning:

services:
  loki:
    image: grafana/loki:2.9.1
    expose:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/log:/host_log:ro
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    expose:
      - "9080"
    networks:
      - loki

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - loki
    volumes:
      - grafana:/var/lib/grafana
      - provisioning:/etc/grafana/provisioning/
