version: '3'
services:

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: user_wp
      MYSQL_PASSWORD: P@ssw0rd
    restart: always

  wordpress:
    image: wordpress:php7.4-fpm-alpine
    volumes:
      - ./data/html:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_PASSWORD: P@ssw0rd
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress

  exporter-nginx:
    image: nginx/nginx-prometheus-exporter
    depends_on:
      - nginx
    ports:
      - 9113:9113
    command:
      - -nginx.scrape-uri
      - http://192.168.0.110:8080/nginx_status
    restart: always
    networks:
      - wordpress_net

  exporter-mysql:
    image: bitnami/mysqld-exporter
    depends_on:
      - mysql
    ports:
      - 9104:9104
    restart: always
    environment:
      DATA_SOURCE_NAME: "user_wp:P@ssw0rd@(mysql:3306)/db_wordpress"
    networks:
      - wordpress_net

  exporter-wordpress:
    image: alexandreio/wordpress_exporter
    depends_on:
      - wordpress
      - nginx
    ports:
      - 9850:9850
    restart: always
    environment:
      WORDPRESS_DB_HOST: 192.168.0.110
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_DB_PASSWORD: P@ssw0rd
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - wordpress_net

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    restart: always
    networks:
      - wordpress_net

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - wordpress_net

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
    ports:
      - '9093:9093'
    networks:
      - wordpress_net

networks:
  wordpress_net: