global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: /metrics

  - job_name: 'wordpress'
    static_configs:
      - targets: ['exporter-wordpress:11011']
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['exporter-nginx:9113']
    metrics_path: /metrics

  - job_name: 'mysql'
    static_configs:
      - targets: ['exporter-mysql:9104']
    metrics_path: /metrics