global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    infra: observability

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'wordpress-exporter'
    static_configs:
      - targets: ['wordpress-exporter:8888']
    metrics_path: /metrics

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: /metrics
    
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']
    metrics_path: /metrics
          
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.+)'
        replacement: '$1'
        action: replace

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://otus.ru
        - http://nginx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [instance]
        target_label: resource_url
      - regex: ^http://(.+)$
        replacement: $1
        target_label: resource_url

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
