global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:8000']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
      - source_labels: [ __address__ ]
        target_label: port
        regex: '([^:]+):([0-9]+)?'
        replacement: '${2}'
#    relabel_configs:
#      - replacement: "production"
#        target_label: "env"
#        action: "replace"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093