global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - chat_id: 2130189693
        parse_mode: 'HTML'
        bot_token: '5805976749:AAEvztRdbyAzW55vwQpd7AhiziqKto6OMmk'
