global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: /metrics

  - job_name: 'wordpress'
    static_configs:
      - targets: ['exporter-wordpress:9850']
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['exporter-nginx:9113']
    metrics_path: /metrics

  - job_name: 'mysql'
    static_configs:
      - targets: ['exporter-mysql:9104']
    metrics_path: /metrics

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://192.168.0.110:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.110:9115

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.168.0.110:9093